version: '3'
services:
  apiData:
    build:
      context: .
      dockerfile: Dockerfile
    image: oppen-bingo-back
    ports:
      - '8080:8080'
    environment:
      - ADDITIONAL_OPTS=-Doracle.jdbc.timezoneAsRegion=false -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: always